#!/bin/sh
#global.bootm.image=/mnt/mmc0.1/boot/Image
#global.bootm.oftree=/mnt/mmc0.1/boot/${global.bootm.fdt}
global.bootm.image=/mnt/mmc0.1/boot/fitImage@${global.boot.fitnode}
#global.bootm.initrd=<path to initrd>
global linux.bootargs.dyn.root="root=/dev/mmcblk0p2 rootfstype=ext4 rootwait ro rauc.slot=system1"
