#!/bin/sh
usb
sleep 1
global.loglevel=7
global.bootm.image=/mnt/disk0.0/boot/Image
global.bootm.oftree=/mnt/disk0.0/boot/${global.bootm.fdt}
global linux.bootargs.dyn.root="dwc_otg.lpm_enable=0 root=/dev/sda1 rootfstype=ext4 rootwait ro rauc.slot=_external_"
