#!/bin/sh

global.bootm.image=/mnt/mmc1.0/boot/Image
global.bootm.oftree=/mnt/mmc1.0/boot/${global.bootm.fdt}
#global.bootm.initrd=<path to initrd>
global linux.bootargs.dyn.root="root=/dev/mmcblk1p1 rootfstype=ext4 rootwait ro rauc.slot=external"
