#!/bin/sh
global.bootm.image=/mnt/mmc0.0/boot/Image
global.bootm.oftree=/mnt/mmc0.0/boot/${global.bootm.fdt}
#global.bootm.image=/mnt/mmc0.0/boot/fitImage@${global.boot.fitnode}
#global.bootm.initrd=<path to initrd>
global linux.bootargs.dyn.root="root=/dev/mmcblk0p1 rootfstype=ext4 rootwait ro rauc.slot=system0 ${global.nvram}"
