#!/bin/sh

detect mmc0
global.autoboot_abort_key="ctrl-c"
global.boot.default="usb bootchooser sd"
global.bootchooser.state_prefix="state.bootstate"
global.bootchooser.targets="system0 system1"
global.boot.watchdog_timeout=100
echo "Init USB. kick it twice to allow disk power up"
usb
sleep 1
usb
