#!/bin/sh

detect mmc0
global.autoboot_abort_key="ctrl-c"
global.boot.default="usb bootchooser noboot"
global.bootchooser.state_prefix="state.bootstate"
global.bootchooser.targets="system0 system1"
global.bootchooser.reset_attempts="power-on"
global.bootchooser.retry=1
global.boot.watchdog_timeout=100
